# fly.toml file generated for sparkling-resonance-7401 on 2022-11-11T17:50:03+05:30

app = "sparkling-resonance-7401"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[deploy]

[processes]
  app = "node app.js"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 60000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]

  [[services.script_checks]]
    command       = "/app/health_check.sh | tee output.txt"
    grace_period  = "10s"
    interval      = 86400
    restart_limit = 0
    timeout       = 2000